#!/usr/bin/env python3
"""
generate-env.py — read inventory.yaml, write .env.platform with every
resource's real connection URL, derived once instead of hand-copied into
N different tool configs.

Usage:
    python3 generate-env.py [path/to/inventory.yaml]   # defaults to ./inventory.yaml

What this does NOT do:
    - It does not read or write any secret (bearer tokens, admin tokens, API
      keys). Those live in the actual deployed config on each host (envoy.yaml,
      rlmgw.env, etc.) and were deliberately kept out of inventory.yaml, which
      is not access-controlled the way a secrets store is. This script emits
      clearly-marked placeholder lines for each one; fill them in by hand,
      and keep .env.platform out of git (see the .gitignore note printed below).
    - It does not run automatically and nothing reads inventory.yaml on its
      own otherwise (see DEPLOYMENT_GUIDE.md's Prerequisites section) --
      this script is the one deliberate exception, and it's read-only: it
      never edits inventory.yaml, only reads it.
    - It does not deploy anything or change any running service. It just
      writes a file you (or another tool) can `source`.

Re-run this any time inventory.yaml changes -- the output is meant to be
regenerated, not hand-edited afterward.
"""
import sys
import pathlib

try:
    import yaml
except ImportError:
    print("error: this script needs PyYAML -- run: pip3 install pyyaml", file=sys.stderr)
    sys.exit(1)


def slug(hostname: str) -> str:
    return hostname.upper().replace("-", "_")


def main() -> int:
    inv_path = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "inventory.yaml")
    if not inv_path.exists():
        print(f"error: {inv_path} not found", file=sys.stderr)
        return 1

    inv = yaml.safe_load(inv_path.read_text())
    lines: list[str] = [
        "# Generated by generate-env.py from inventory.yaml -- do not hand-edit,",
        "# re-run the script instead. Lines marked REPLACE_ME are secrets that",
        "# deliberately don't live in inventory.yaml -- see that file's real",
        "# deployed location in DEPLOYMENT_GUIDE.md's \"Where Configuration",
        "# Actually Lives\" section before filling them in.",
        "",
    ]

    g = inv.get("global", {})
    if g.get("gateway_url"):
        lines.append(f'ENVOY_URL={g["gateway_url"]}')
        lines.append("ENVOY_TOKEN=REPLACE_ME  # the bearer token baked into envoy.yaml's Lua script")
    if g.get("rlmgw_url"):
        lines.append(f'RLMGW_URL={g["rlmgw_url"]}')
    lines.append("")

    for m in inv.get("mac_workstations", []):
        name = slug(m["hostname"])
        port = m.get("ollama_port")
        if port:
            lines.append(f'{name}_OLLAMA_URL=http://{m["ip"]}:{port}')
    if inv.get("mac_workstations"):
        lines.append("")

    jn = inv.get("jetson_nodes", {})
    port = jn.get("ollama_port")
    for node in jn.get("nodes", []):
        name = slug(node["hostname"])
        lines.append(f'{name}_OLLAMA_URL=http://{node["ip"]}:{port}')
    if jn.get("nodes"):
        lines.append("")

    for host in inv.get("linux_gpu_hosts", []):
        if "vllm-turboquant" in host.get("services", []):
            name = slug(host["hostname"])
            lines.append(f'{name}_VLLM_URL=http://{host["ip"]}:8000')
    lines.append("")

    oc = inv.get("openshift_cluster", {})
    api_url = oc.get("api_url", "")
    if api_url and "vllm-turboquant" in (
        oc.get("namespaces", {}).get("serving", {}).get("services", [])
    ):
        # Best-effort Route hostname from the naming convention this guide
        # uses elsewhere (<service>-<namespace>.apps.<cluster-domain>) --
        # this is a guess at the pattern, NOT a lookup. Confirm with
        # `oc get route vllm-turboquant -n ai-serving` before trusting it.
        cluster_domain = api_url.split("://api.", 1)[-1].split(":")[0] if "://api." in api_url else None
        if cluster_domain:
            lines.append(
                f"# Best-effort guess from the api.{cluster_domain} naming pattern -- "
                f"confirm with: oc get route vllm-turboquant -n ai-serving"
            )
            lines.append(f"OPENSHIFT_VLLM_URL=http://vllm-turboquant-ai-serving.apps.{cluster_domain}")
            lines.append("")

    out_path = pathlib.Path(".env.platform")
    out_path.write_text("\n".join(lines) + "\n")

    gitignore = pathlib.Path(".gitignore")
    already_ignored = gitignore.exists() and ".env.platform" in gitignore.read_text()
    print(f"Wrote {out_path.resolve()}")
    if not already_ignored:
        print(
            "NOTE: .env.platform is not in .gitignore yet, and it will contain "
            "real internal IPs (and secrets once you fill them in) -- add it "
            "before committing anything in this directory."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
